#.NET Framework
# C# console application 

#automatically triggers the Master branch for every commit
trigger:
- Master

#aget pool
pool:
  name: Default

#variable to be used on steps
variables:
 buildConfiguration: 'Release'


steps:

#To build the project file
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build --configuration $(buildConfiguration)'
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'


#To publish the build arifact to a directory for deployment
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish --cofiguration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
