#.NET Framework
# C# console application 

trigger:
- master

pool:
  name: Default

variables:
 configuration: 'Release'

steps:
  - script: dotnet build --configuration $(configuration)
    displayName: 'dotnet build --configuration $(configuration)'
