#.NET Framework
# C# console application 

#automatically triggers the Master branch for every commit
trigger:
- Master

#aget pool
pool:
  name: Default

#variable to be used on steps
variables:
 buildConfiguration: 'Release'


steps:
#installing dotnet core 

  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'runtime'
      version: '7.0.102'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build $(buildConfiguration)'
    inputs:
      command: build
      projects: 'HelloWorld/HelloWorld.csproj'
      arguments: '--configuration $(buildConfiguration)'

#To build the project file
#  - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'

#To publish the build arifact to a directory for deployment
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish --cofiguration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
